Repository yaptide/ui, pull requests merged in 2023-10, with the labels that each got.

#1267 Change token verification
  src/services/AuthService.tsx
Labels: EuroHPC

#1275 Use name of page in `key` in results
  src/JsRoot/GraphData.tsx
  src/WrapperApp/components/Results/ResultsPanel.tsx
  src/shared/components/tooltip/InfoTooltip.tsx
Labels: bug, EuroHPC

#1289 Resolves 1287 Enable fluka simulation selection
  src/WrapperApp/components/Simulation/RunSimulationForm.tsx
Labels: Fluka

#1302 Add documentation button
  src/WrapperApp/components/NavDrawer/NavDrawerList.tsx
Labels: feature, EuroHPC

#1288 1280 unhandled keycloak log in failure
  package-lock.json
  package.json
  src/App.tsx
  src/ThreeEditor/components/Dialog/ClearHistoryDialog.tsx
  src/ThreeEditor/components/Dialog/CustomDialog.tsx
  src/ThreeEditor/components/Dialog/EditProjectInfoDialog.tsx
  src/ThreeEditor/components/Dialog/LoadFileDialog.tsx
  src/ThreeEditor/components/Dialog/NewProjectDialog.tsx
  src/ThreeEditor/components/Dialog/RejectKeycloakUserDialog.tsx
  src/ThreeEditor/components/Dialog/RunSimulationDialog.tsx
  src/ThreeEditor/components/Dialog/SaveFileDialog.tsx
  src/ThreeEditor/components/Editor/EditorAppBar/EditorAppBar.tsx
  src/ThreeEditor/components/Editor/EditorAppBar/components/EditorTitlebar.tsx
  src/ThreeEditor/components/Editor/EditorMenu/EditorMenu.tsx
  src/ThreeEditor/components/ZoneManagerPanel/BooleanAlgebra/OperationToggle.tsx
  src/ThreeEditor/components/ZoneManagerPanel/ZoneManagerPanel.tsx
  src/ThreeEditor/js/Storage.js
  src/WrapperApp/components/InputEditor/InputFilesEditor.tsx
  src/WrapperApp/components/Panels/LoginPanel.tsx
  src/WrapperApp/components/Results/ResultsPanel.tsx
  src/WrapperApp/components/Simulation/RunSimulationForm.tsx
  src/WrapperApp/components/Simulation/SimulationCard.tsx
  src/WrapperApp/components/Simulation/SimulationCardGrid.tsx
  src/services/AuthService.tsx
  src/services/DialogService.tsx
  src/services/GenericContext.ts
  src/services/KeycloakAuthService.tsx
  src/services/LoaderService.tsx
  src/services/keycloakConfig.ts
Labels: EuroHPC

#1281 nginx configuration improved
  nginx.conf
Labels: feature, EuroHPC

#1314 Add keycloak token verification
  src/services/AuthService.tsx
Labels: EuroHPC
